#!/bin/bash

###
# Graylog Twilio SMS/Whatsapp Notification Integration 
###

# Script arguments
EVENT_TITLE="$1"
SOURCE_IP="$2"
USERNAME="$3"
TIMESTAMP="$4"
NOTIFICATION_RECIPIENTS="$5"

# Globals
LOCALLOG=false
LOG_FILE="/var/log/sms_notification.log"
TWILIO_ACC_ID="<redacted>"
TWILIO_ACC_SECRET="<redacted>"
NOTIFICATION_SENDER="<redacted>"
NOTIFICATION_RECIPIENTS_PARSED=()

# Check if required arguments are provided
if [ "$#" -ne 5 ]; then
    echo "Usage: $0 <event_title> <source_ip> <username> <timestamp> <notification recipient / multiple seperated with semicolon>"
    exit 1
fi

if [[ "$NOTIFICATION_RECIPIENTS" == *";"* ]]; then
    IFS=';'
    read -ra NOTIFICATION_RECIPIENTS_PARSED <<< "$input_string"
    IFS=$' \t\n'
else 
    NOTIFICATION_RECIPIENTS_PARSED+=("$NOTIFICATION_RECIPIENTS")
fi

# Notification body
NOTIFICATION_BODY=(cat << 'EOF'
$EVENT_TITLE @ $TIMESTAMP (UTC)
From: $SOURCE_IP
User: $USERNAME
EOF
)

# Twilio notification action
# curl -X POST -d "Body=Hi there, this is a test message from cURL" -d "From=$TWILIO_NUMBER" -d "To=$TO_NUMBER" "https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACCOUNT_SID/Messages" -u "$TWILIO_ACCOUNT_SID:$TWILIO_AUTH_TOKEN"

for (mobileNr in ${NOTIFICATION_RECIPIENTS_PARSED[@]}); do
    curl 'https://api.twilio.com/2010-04-01/Accounts/$TWILIO_ACC_ID/Messages.json' -X POST \
    --data-urlencode 'To=$mobileNr' \
    --data-urlencode 'From=$NOTIFICATION_SENDER' \
    --data-urlencode 'Body=$NOTIFICATION_BODY' \
    -u $TWILIO_ACC_ID:$TWILIO_ACC_SECRET
    sleep 1
done

# Local logging
if [LOCALLOG] && [ -f $LOG_FILE]; then
    echo "$TIMESTAMP: SMS Notification: $EVENT_TITLE by $SOURCE_IP to $NOTIFICATION_RECIPIENTS" >> $LOG_FILE
fi

# Exit successfully
exit 0
